FROM ubuntu:16.04 

# Set working directory
WORKDIR /mlperf

# update and upgrade
RUN apt-get update && apt-get upgrade -y

# apt installs 
RUN apt-get install -y \
    git \ 
    make \
    build-essential \ 
    libssl-dev \ 
    zlib1g-dev \ 
    libbz2-dev \
    libreadline-dev \
    libsqlite3-dev \
    wget \
    curl \
    llvm \
    libncurses5-dev \
    libncursesw5-dev \
    xz-utils \
    tk-dev \
    cmake \ 
    unzip \
    python

# pyenv Install
RUN git clone https://github.com/pyenv/pyenv.git .pyenv

ENV HOME /mlperf
ENV PYENV_ROOT $HOME/.pyenv
ENV PATH $PYENV_ROOT/shims:$PYENV_ROOT/bin:$PATH

# Install Anaconda
RUN PYTHON_CONFIGURE_OPTS="--enable-shared" pyenv install anaconda3-5.3.0
RUN pyenv rehash
RUN pyenv global anaconda3-5.3.0

# Pytorch setup
# Set anaconda root directory
ENV CMAKE_PREFIX_PATH /mlperf/.pyenv/shims/../

# Install basic dependencies
RUN conda install numpy pyyaml setuptools cmake cffi typing
RUN conda install -c intel mkl mkl-include
RUN conda install -c mingfeima mkldnn

# Clone source
WORKDIR /mlperf/github
RUN git clone --recurse-submodules https://github.com/pytorch/pytorch
WORKDIR /mlperf/github/pytorch

# Install
RUN python setup.py install

# Setup Recomendation
WORKDIR /mlperf/ncf
ADD . /mlperf/ncf

RUN python -m pip install -U pip
RUN pip install -r requirements.txt

ENTRYPOINT ["/bin/bash"]
