FROM ubuntu:16.04

WORKDIR /research

RUN apt-get update && apt-get upgrade -y && apt-get autoremove && apt-get autoclean
RUN apt-get install -y --no-install-recommends \
    ca-certificates \
    build-essential \
    git \
    python \
    python-pip \
    python3-pip \
    python3-setuptools \
    virtualenv \
    htop

ENV HOME /research
ENV PYENV_ROOT $HOME/.pyenv
ENV PATH $PYENV_ROOT/shims:$PYENV_ROOT/bin:$PATH

RUN python3 -m pip install -U pip
RUN pip3 install virtualenv
RUN pip3 install virtualenvwrapper
RUN pip3 install --upgrade numpy scipy sklearn 

# Mount data into the docker
ADD . /research/reinforcement
WORKDIR /research/reinforcement

RUN pip3 install --upgrade setuptools
RUN pip3 install -r minigo/requirements.txt
RUN pip3 install https://storage.googleapis.com/intel-optimized-tensorflow/tensorflow-1.11.0-cp35-cp35m-linux_x86_64.whl
ENTRYPOINT ["/bin/bash"]
